runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /static
  static_dir: static/
- url: .*
  script: mugglevn.wsgi.application

# Only pure Python libraries can be vendored
# Python libraries that use C extensions can
# only be included if they are part of the App Engine SDK
# Using Third Party Libraries: https://cloud.google.com/appengine/docs/python/tools/using-libraries-python-27
libraries:
- name: MySQLdb
  version: 1.2.5
- name: PIL
  version: 1.1.7
- name: ssl
  version: 2.7.11
- name: six
  version: 1.9.0

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^env/.*$
- ^dumpdata/.*$
- ^staticfile_dirs/.*$

env_variables:
    GAE_USE_SOCKETS_HTTPLIB : 'true'
    SECRET_KEY : '88zmp9zmk0yhm$yhj0q%l-3iahv23crg9-5udv1q4_^p(z(w&b'
    ALLOWED_HOSTS : '.mugglevn.xyz, 127.0.0.1, .localhost, .mugglevn.appspot.com'
    DEBUG : 'False'
    DB_USER : 'mugglevn'
    DB_PASSWORD : 'MkfTdLyhshSQ'
    GS_ACCESS_KEY_ID : 'GOOGYHHOMP2D2EZTEVOV'
    GS_SECRET_ACCESS_KEY : 'zv37xNd+qB8Z5CwtW6SwlabAymTf3BnZH95oNvih'
    GS_BUCKET_NAME : 'mugglevngcs'
    SOCIAL_AUTH_GITHUB_KEY : '6ce2230fb03cbede49a2'
    SOCIAL_AUTH_GITHUB_SECRET : '9a975ce7e349e76f25a0527472cd1144bd8b11df'
    SOCIAL_AUTH_FACEBOOK_KEY : '329354177482815'
    SOCIAL_AUTH_FACEBOOK_SECRET : '832a20ee73d427b0641f6fede792d6a9'
    SOCIAL_AUTH_GOOGLE_OAUTH2_KEY : '938522967327-lhrvv9gnpmtd9d4vrrthoo4h37ccbipn.apps.googleusercontent.com'
    SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET : 'wPL66pOX9Jcdn4LRkkbG-969'
    SOCIAL_AUTH_LINKEDIN_OAUTH2_KEY : '81eof69zitt8st'
    SOCIAL_AUTH_LINKEDIN_OAUTH2_SECRET : 'PQdOQM61kl4m6uN3'